// <auto-generated />
using System;
using App.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace App.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("App.Data.Email", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Beschreibung")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Gesendet")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Emails");
                });

            modelBuilder.Entity("App.Data.EmailPerson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("Email")
                        .HasColumnType("int");

                    b.Property<int?>("Person")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EmailPersonen");
                });

            modelBuilder.Entity("App.Data.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Emailadresse")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nachname")
                        .HasColumnType("longtext");

                    b.Property<string>("Vorname")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Personen");
                });
#pragma warning restore 612, 618
        }
    }
}
